### ISSUE TITLE
RSS icon position issue

### ISSUE THREAD

**Issue by rohanvakharia** [klaussilveira/gitlist#533]
Hi I have just found that RSS icon does displayed on proper position.

I have studied the code and create a fix. 

Please someone add this fix:
```css
.rss-icon {
    vertical-align: super;
}
```

File which need to be changed is: `themes/default/less/breadcrumbs.less` (line number: 32).
