### ISSUE TITLE
Not listing repositories

### ISSUE THREAD

**Issue by soknet** [klaussilveira/gitlist#905]
Hi!

Can someone publish an example of a config/config.yml file?

I'm struggling to get my installation working, and I don't get it to list my repos.

My repos section looks like this, right now:
```
# List of directories containing repositories
  default_repository_dir: /var/www/bare_repo_proyect.git
  repositories:
    - 
        label: main
        target: /var/www/bare_repo_proyect.git
```

It's a bare repo, but I have tried with normal ones, and I don't get it working.

It just shows this. No matter what I write in the config/config.yml file.

![image](https://user-images.githubusercontent.com/6514444/169032359-0a79e280-d05c-409b-9ff1-670b95f5c14e.png)

Thank you!
