### ISSUE TITLE
Support needed on installing

### ISSUE THREAD

**Issue by satel-kalletuulos** [klaussilveira/gitlist#920]
I'm trying to install Gitlist 2.0 from zip file to Ubuntu 22.04 server, running Apache2. The server has PHP 8.1.

The normal WWW directory, i.e. from where pages are served, is: ```/var/www/html```

Gitlist is unzipped installed in directory: ```/var/www/html/gitlist```

File ```/etc/apache2/conf-enabled/gitlist.conf```` is as follows:
```
Alias /gitlist /var/www/html/gitlist/public
<Directory /var/www/html/gitlist>
  Options FollowSymLinks
  AllowOverride All
</Directory>
```

The config/config.yml has been configured as follows:
```
  # List of directories containing repositories
  default_repository_dir: /var/www/html/git-mirror/github.com
  repositories:
    - '%env(default:default_repository_dir:DEFAULT_REPOSITORY_DIR)%'
....
  # How many levels should be recursively traversed looking for repositories
  repository_depth: '1'
```
I have cloned two repositories from Github as follows:
```
/var/www/html/git-mirror/github.com/meta-rust/meta-rust.git
/var/www/html/git-mirror/github.com/nxp-imx/imx-manifest.git
```
When I open the gitlist URL, I get following page (styled with Markdown, copy&paste from Chrome):

--8<---8<---
[GitList](http://192.168.0.226/gitlist/)
[Repositories](http://192.168.0.226/gitlist/)
[Help](https://github.com/klaussilveira/gitlist/wiki)
[Report an Issue](https://github.com/klaussilveira/gitlist/issues)
[imx-manifest.git](http://192.168.0.226/gitlist/imx-manifest.git) [RSS](http://192.168.0.226/gitlist/imx-manifest.git/feed/imx-linux-kirkstone.rss)
Unnamed repository; edit this file 'description' to name the repository.
[meta-rust.git](http://192.168.0.226/gitlist/meta-rust.git) [RSS](http://192.168.0.226/gitlist/meta-rust.git/feed/master.rss)
Unnamed repository; edit this file 'description' to name the repository.
© 2012 - 2022 Powered by [GitList.org](https://gitlist.org/)
--8<---8<---

When I try to click either of those repositories, I just get error "Not Found, The Requested URL was not found on this server." It seems that gitlist does not create some logical links when it scans directories for repositories. Anyway, there are no error messages on the ```var/log/prod.log``` , only following is printed:
```
[2022-10-18T17:07:36.951207+03:00] request.INFO: Matched route "repository_list". {"route":"repository_list","route_parameters":{"_route":"repository_list","_controller":"GitList\\App\\Controller\\Repository::list"},"request_uri":"http://192.168.0.226/gitlist/","method":"GET"} []
```
Could you please give a simple example, how to configure gitlist to work with just couple of cloned repositories?
