### ISSUE TITLE
Problem when adding gits

### ISSUE THREAD

**Issue by eskopp** [klaussilveira/gitlist#933]
Hi guys, 
I have Ubuntu 22.04 LTS and a current PHP version. The installation of gitlist worked. There were no problems that I noticed and the website works. 
![image](https://github.com/klaussilveira/gitlist/assets/129506395/35fa87a5-21b0-4cf7-8ac6-dc56d003baf5)

Apache 2 - Site Config: 
```bash
<VirtualHost *:80>
     ServerAdmin ***
     DocumentRoot /var/www/***/public
     ServerName ***
     <Directory /var/www/***/public>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
          <IfModule mod_dav.c>
            Dav off
          </IfModule>
        SetEnv HOME /var/www/***/public
        SetEnv HTTP_HOME /var/www/***/public
     </Directory>
     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

The config of gitlist: 
I only changed the git directory to ``/data/git``. 
```yml
# GitList configuration
parameters:
  # Web application title
  title: GitList

  # Locale configuration
  locale: en

  # Theme
  theme: default

  # Navigation links
  navigation:
    -
      label: Help
      target: https://github.com/klaussilveira/gitlist/wiki
    -
      label: Report an Issue
      target: https://github.com/klaussilveira/gitlist/issues

  # List of directories containing repositories
  default_repository_dir: /data/git
  repositories:
    - '%env(default:default_repository_dir:DEFAULT_REPOSITORY_DIR)%'

  # List of repositories to exclude
  exclude_repositories:
    - /var/example/gitlist

  # How many levels should be recursively traversed looking for repositories
  repository_depth: '0'

  # Commits to show per page
  commits_per_page: 10

  # Blob viewer: simple, codemirror or ace
  default_blob_viewer: ace

  # Show file size in tree
  tree_show_file_size: false

  # Show last commit in tree
  tree_show_last_commit: true

  # Default binary paths
  git_path: /usr/bin/git
  hg_path: /usr/bin/hg

  secret: '%env(APP_SECRET)%'

  avatar_url: '//gravatar.com/avatar'
  avatar_config: []

  commit_date_format: 'Y-m-d H:i:s'
  commit_group_date_format: 'F j, Y'
  commit_list_date_format: 'Y-m-d H:i:s'

  ssh_clone_url: 'git@gitlist.org:%s.git' # %s will be replaced by the repository name
  https_clone_url: 'https://gitlist.org/%s.git' # %s will be replaced by the repository name

  # Route validators
  valid_repository_name: '[a-zA-Z0-9\-\_\.]+'
  #valid_commitish_format: '.+'
  valid_commitish_format: '[a-zA-Z0-9\_\.\-\/]+'
```

The website still works up to this point. However, as soon as I clone a git into the folder, everything goes wrong and I get an error 500. see picture
![image](https://github.com/klaussilveira/gitlist/assets/129506395/d6fd9cea-0aec-4853-887f-f9eeabe0f801)
But as soon as I completely empty the folder again, everything is fine and the page works again. 
What am I doing wrong?
